version: 2
jobs:
  build:
    
    working_directory: ~/TS3AudioBot

    docker:
      - image: amd64/debian:buster

    steps:
      - checkout
      - run: apt update && apt full-upgrade -y && apt install wget sudo zip -y
      - run: wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - run: dpkg -i packages-microsoft-prod.deb
      - run: rm packages-microsoft-prod.deb
      - run: sudo apt update
      - run: sudo apt install apt-transport-https -y
      - run: sudo apt update
      - run: sudo apt install dotnet-sdk-3.1 -y
      - run: dotnet build --framework netcoreapp3.1 --configuration Release TS3AudioBot
      - run: mkdir artifacts
      - run: cd artifacts && zip -r artifacts.zip ~/TS3AudioBot/TS3AudioBot/bin/Release/netcoreapp3.1
      
      - store_artifacts:
          path: ~/TS3AudioBot/artifacts
